//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by microsip.rc
//
#define _GLOBAL_AUTO_ANSWER_VALUE       0
#define _GLOBAL_FORCE_INCODEC           0
#define IDD_SETTINGS_OFFSET_00          0
#define _GLOBAL_SOUND_EVENTS            1
#define _GLOBAL_MULTI_MODE              1
#define _GLOBAL_PADDING_TOP             10
#define _GLOBAL_PADDING_BOTTOM          10
#define IDD_RINGIN_OFFSET_1             15
#define IDD_ACCOUNT_OFFSET_SIP_SERVER   27
#define ID_STATUSBAR                    101
#define IDD_FORM_WEB                    101
#define IDD_MICROSIP_DIALOG             102
#define IDC_SINGLE_MODE                 102
#define IDC_SYSLINK_SINGLE_MODE         103
#define IDC_PREVIEW                     104
#define ID_PREVIEW                      105
#define IDC_LOCAL_DTMF                  106
#define IDC_SYSLINK_LOCAL_DTMF          107
#define IDC_BITRATE_264                 108
#define IDC_BITRATE_263                 109
#define IDC_EDIT_AUTHID                 110
#define IDC_SYSLINK_AUTHID              111
#define IDC_ENABLE_LOG                  112
#define IDC_SYSLINK_DISPLAY_PASSWORD    113
#define IDC_CALLER_USER_AGENT           114
#define IDC_RING                        115
#define IDC_RING1                       115
#define IDD_ACCOUNT_PIN                 116
#define IDC_BALANCE                     117
#define IDC_BALANCE_LABEL               118
#define ID_ALWAYS_ON_TOP                119
#define IDD_REG1                        120
#define IDD_REG2                        121
#define IDD_REG3                        122
#define IDC_SYSLINK_REG                 123
#define IDD_ACCOUNT_REG                 124
#define IDD_BUTTONS                     125
#define IDC_BUTTON_HAND                 126
#define IDC_BUTTON_FLOOR                127
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_EN                   128
#define IDC_BUTTON_FR                   129
#define IDI_EXIT                        129
#define IDC_BUTTON_SP                   130
#define IDD_RINGIN                      131
#define IDC_BUTTON_RU                   131
#define IDD_ACCOUNT                     132
#define IDC_BUTTON_CN                   132
#define IDC_BUTTON_AR                   133
#define IDC_REMEMBER_PASSWORD           134
#define IDC_EDIT_DISPLAYNAME            136
#define IDI_DEFAULT                     138
#define IDD_CONFERNCE                   139
#define IDC_EDIT_CONFERENCE_CODE        140
#define IDC_ACCOUNT_WELCOME             141
#define IDC_DENY_INCOMING               142
#define IDC_SYSLINK_DENY_INCOMING       143
#define IDC_REWRITE                     144
#define IDC_SYSLINK_REWRITE             145
#define IDC_DIRECTORY                   146
#define IDC_SYSLINK_DIRECTORY           147
#define IDI_UNKNOWN                     147
#define IDC_BUTTON_MUTE                 148
#define IDI_OFFLINE                     148
#define IDI_BUSY                        149
#define IDI_AWAY                        151
#define IDI_ONLINE                      152
#define IDR_MENU_CONTACT                153
#define IDC_DECLINE                     153
#define IDC_ANSWER                      154
#define IDD_ADD                         155
#define IDC_AUDIO                       155
#define IDD_SETTINGS                    156
#define IDI_ACTIVE                      156
#define IDD_MESSAGES                    158
#define IDC_IGNORE                      158
#define IDC_SYSLINK_ENABLE_LOG          160
#define IDR_MENU_TRAY                   161
#define IDC_VOLUME_INPUT                161
#define IDC_BUTTON_MUTE_OUTPUT          162
#define IDD_DIALER                      163
#define IDC_BUTTON_MUTE_INPUT           163
#define IDD_CONTACTS                    164
#define IDI_MUTE_OUTPUT                 164
#define IDI_MUTED_OUTPUT                165
#define IDI_MUTE_INPUT                  166
#define IDI_MUTED_INPUT                 167
#define IDC_VOLUME_INPUT_VALUE          168
#define IDC_FORCE_CODEC                 169
#define IDC_SYSLINK_FORCE_CODEC         170
#define IDC_EC                          171
#define IDI_BLANK                       172
#define IDC_SYSLINK_EC                  172
#define IDC_EDIT_API_ID                 173
#define IDC_CALL_SKYPE                  174
#define IDD_ACCOUNT_CUSTOM              175
#define IDI_CALL_OUT                    175
#define IDI_CALL_IN                     176
#define IDD_TRANSFER                    177
#define PAGE_WIDTH                      177
#define IDD_CALLS                       178
#define IDI_CALL_MISS                   178
#define IDDELETE                        178
#define IDC_SYSLINK_DELETE              179
#define ID_CALL_PICKUP                  180
#define IDI_CLOSE                       181
#define IDC_FIRST                       181
#define IDI_CLOSE_2                     182
#define IDI_LOGO                        183
#define IDR_MENU_TABS                   184
#define IDD_REG_STEP1                   185
#define IDD_REG_STEP2                   186
#define IDD_REG_STEP3                   187
#define IDR_MENU_MESSAGES               189
#define IDD_DIALOG1                     191
#define IDD_DIALOG2                     194
#define IDD_DLGTEXT                     194
#define IDI_INACTIVE                    196
#define IDI_MUTE                        197
#define IDI_MUTED                       198
#define IDI_TRANSFER                    199
#define IDI_HOLD                        201
#define IDI_END                         202
#define IDI_VIDEO                       203
#define IDI_MESSAGE                     204
#define IDC_ACTIONS                     205
#define IDC_BUTTON_END                  206
#define IDC_CUSTOM_INI                  207
#define IDI_VOICEMAIL                   207
#define IDC_BROWSE_INI                  208
#define IDC_DEFAULT_INI                 209
#define IDI_HOMEPAGE                    209
#define IDC_VMCOUNT                     210
#define IDI_VIBER                       210
#define IDC_ATTDTRANSFER                211
#define IDC_DONTDIST                    211
#define IDC_CONFERENCE                  212
#define IDB_PHONERING                   212
#define IDC_FOP2                        212
#define IDC_BUTTON_MODE_SELECTION       213
#define IDC_ATTDTRANSFER2               213
#define IDC_TABCLOSE                    213
#define IDC_TOCELL                      214
#define IDC_MERGE                       215
#define IDI_MODE_HEADSET                216
#define IDI_MODE_SPEAKER                217
#define IDR_GIF1                        217
#define IDR_RINGING                     217
#define IDC_OPENDOOR                    217
#define IDR_MICROSIP                    218
#define IDR_MICROSIP1                   220
#define IDI_ICONIDLE                    229
#define IDI_ICONNOT                     230
#define IDD_FOP2                        231
#define IDI_FOP2                        234
#define IDD_DLGSUPERS                   235
#define IDD_DIALOGOOO                   237
#define IDD_DLGPHONEOOO                 238
#define IDI_ICONOOO                     239
#define IDI_ICONINOTES                  240
#define IDI_ICONLISTENER                242
#define IDD_DLGTOP                      243
#define IDD_DLGBOT                      244
#define IDD_DLGRIGHT                    245
#define IDD_DIALOGIE                    246
#define IDB_UNLOCK1                     250
#define IDB_UNLOCK                      253
#define IDI_UNLOCK                      256
#define IDI_ICONCALLSUPER               258
#define IDI_BTNTEXT                     259
#define IDI_BTNSENDLEASE                260
#define IDI_BTNEBILL                    261
#define IDI_BTNTAGCOMP                  262
#define IDI_BTNMOVE                     263
#define IDI_BTNIMAGE                    264
#define IDI_BTNCALLRENEWAL              265
#define IDI_BTNCALLRENT                 266
#define IDI_ICON1                       267
#define IDI_BTNCALLRENTSTATE            267
#define IDI_ICON2                       268
#define IDI_ICON3DAYS                   268
#define IDI_NEW_ICONINOTES              270
#define IDI_ICON3                       271
#define IDI_ICONNEWOOO                  271
#define IDI_ICONMOVEOUT                 272
#define IDI_ICON4                       273
#define IDI_ICONTENCOMP                 273
#define IDI_ICON5                       274
#define IDI_ICONCOI                     274
#define IDI_ICON3DNBIG                  275
#define IDI_ICONLRBIG                   276
#define IDI_ICONMOVEBIG                 277
#define IDI_ICONRENTPBIG                278
#define IDI_ICONTENCOMPBIG              279
#define IDI_ICONRSTATEBIG               280
#define IDI_ICONDISPOBIG                281
#define IDI_ICONPROSPBIG                282
#define IDI_ICONCOIBIG                  283
#define IDI_ICONSENDLRBIG               284
#define IDI_ICONLBBIG                   285
#define IDI_ICON6                       286
#define IDI_ICONSUPERTEXTBIG            286
#define IDI_ICONPAYMENTBIG              287
#define IDI_ICON7                       288
#define IDI_ICONCOMPBIG                 288
#define IDI_ICON8                       289
#define IDI_ICONPROSPECTBIG             289
#define IDD_DIALOGTAGPROSP              290
#define IDI_ICON9                       291
#define IDI_ICONSUPERCALLBIG            291
#define IDI_ICON10                      292
#define IDI_ICONN                       293
#define IDI_ICONNEWINOTS                293
#define IDC_DELETE                      1009
#define IDC_CALLER_NAME                 1012
#define IDC_EDIT_USERNAME               1013
#define IDC_EDIT_PASSWORD               1014
#define IDC_CALLER_ADDR                 1014
#define IDC_EDIT_SERVER                 1015
#define IDC_CALLED                      1015
#define IDC_EDIT_DOMAIN                 1017
#define IDC_EDIT_PROXY                  1018
#define IDC_STUN                        1019
#define IDC_CALL_INFO                   1020
#define IDC_CONTACTS                    1025
#define IDC_EDIT_NUMBER                 1028
#define IDC_EDIT_NAME                   1029
#define IDC_EDIT_TYPE                   1030
#define IDC_AUTO_ANSWER                 1031
#define IDC_VAD                         1032
#define IDC_BROWSE                      1033
#define IDC_DEFAULT                     1034
#define IDC_RINGING_SOUND               1035
#define IDC_DISABLE_H264                1038
#define IDC_DISABLE_H263                1040
#define IDC_LIST                        1048
#define IDC_MESSAGE                     1049
#define IDC_KEY_1                       1050
#define IDC_TAB                         1051
#define IDC_KEY_3                       1052
#define IDC_KEY_4                       1053
#define IDC_KEY_5                       1054
#define IDC_KEY_6                       1055
#define IDC_KEY_7                       1056
#define IDC_KEY_8                       1057
#define IDC_KEY_9                       1058
#define IDC_KEY_STAR                    1059
#define IDC_KEY_0                       1060
#define IDC_KEY_GRATE                   1061
#define ID_TAB                          1065
#define IDC_NUMBER                      1066
#define IDC_KEY_2                       1067
#define IDC_NUMBER2                     1067
#define IDC_CLEAR                       1069
#define IDC_KEY_PLUS                    1070
#define IDC_DISABLE_LOCAL               1071
#define IDC_TRANSPORT                   1072
#define IDC_PUBLIC_ADDR                 1073
#define IDC_SRTP                        1074
#define IDC_ICE                         1075
#define IDC_PRESENCE                    1076
#define IDC_LISTEN_PORT                 1076
#define IDC_CALL                        1078
#define IDC_CALL_END                    1080
#define IDC_VIDEO_CALL                  1081
#define IDC_PUBLISH                     1082
#define IDC_VID_CAP_DEV                 1085
#define IDC_MICROPHONE                  1086
#define IDC_SPEAKERS                    1087
#define IDC_VIDEO                       1089
#define IDC_VIDEO_CODEC                 1089
#define IDC_UPDATES_INTERVAL            1103
#define IDC_SYSLINK_RINGING_SOUND       1104
#define IDC_SYSLINK_AUTO_ANSWER         1105
#define IDC_SYSLINK_DISABLE_LOCAL       1106
#define IDC_SYSLINK_VAD                 1107
#define IDC_SYSLINK_SIP_SERVER          1108
#define IDC_SYSLINK_DISABLE_H264        1108
#define IDC_SYSLINK_SIP_PROXY           1109
#define IDC_SYSLINK_DISABLE_H263        1109
#define IDC_SYSLINK_USERNAME            1110
#define IDC_SYSLINK_AUDIO_CODECS        1110
#define IDC_SYSLINK_DOMAIN              1111
#define IDC_SYSLINK_PASSWORD            1112
#define IDC_SYSLINK_NAME                1113
#define IDC_SYSLINK_ENCRYPTION          1114
#define IDC_SYSLINK_TRANSPORT           1115
#define IDC_SYSLINK_PUBLIC_ADDRESS      1116
#define IDC_SYSLINK_LOCAL_PORT          1117
#define IDC_SYSLINK_PUBLISH_PRESENCE    1118
#define IDC_AUDIO_CODECS_ALL            1118
#define IDC_SYSLINK_STUN_SERVER         1119
#define IDC_AUDIO_CODECS                1119
#define IDC_SYSLINK_ICE                 1120
#define IDC_SYSLINK_PREFIX              1121
#define IDC_SPIN_MODIFY                 1125
#define IDC_SPIN_ORDER                  1127
#define IDC_HOLD                        1128
#define IDC_TRANSFER                    1129
#define IDC_END                         1132
#define IDC_RICHEDIT21                  1133
#define IDC_CALLS                       1135
#define IDC_REG_NUMBER                  1136
#define IDC_REG_CODE                    1137
#define IDC_REG_EMAIL                   1138
#define IDC_REG_PASS1                   1139
#define IDC_SYSLINK1                    1139
#define IDC_REG_PASS2                   1140
#define IDC_REG_COUNTRY                 1140
#define IDC_EDIT1                       1141
#define IDC_EDITTEXT                    1141
#define IDC_ACEDIT                      1141
#define IDC_BUTTON1                     1142
#define IDC_LAST_CALL                   1142
#define IDC_SHOWCALL                    1142
#define IDC_BTNCALLSUPER                1142
#define IDC_BTNSEND                     1142
#define IDC_CLOSE_ALL                   1143
#define IDC_HIDECALL                    1143
#define IDC_BUTTON2                     1144
#define IDC_BUTTON4                     1145
#define IDC_BTNCALLRENEWAL              1145
#define IDC_HIDEBUTTONS                 1145
#define IDC_BUTTON5                     1146
#define IDC_BTNCALLRENTSTATE            1146
#define IDC_SHOWBUTTONS                 1146
#define IDC_BTNCALL3DN                  1147
#define IDC_BTNPROSPECT                 1148
#define IDC_BTNPREQCOI                  1149
#define IDC_BTNCHARGE                   1150
#define IDC_CUSTOM1                     1157
#define IDC_SLIDER1                     1158
#define IDC_VOLUME_OUTPUT               1158
#define IDC_MICROPHONE_1                1159
#define IDC_VM_COUNT                    1159
#define IDC_SPEAKERS_1                  1160
#define IDC_LOGO                        1160
#define IDC_NUMBER1                     1161
#define IDC_ANIMATE3                    1167
#define IDC_PICTURE                     1168
#define IDC_EXPLORER                    1171
#define IDC_EXPLORER1                   1175
#define ID_WEBBROWFOP2                  1176
#define IDC_EXP                         1177
#define IDC_BUTTON3                     1178
#define IDC_BUTTONOOO                   1178
#define IDC_LISTPHONE                   1179
#define IDC_BUTTONDAILY                 1181
#define IDC_BUTTONINOTES                1182
#define IDC_STUNCHECK                   1183
#define ID_BTNDOOR                      1183
#define IDC_TREE1                       1184
#define IDC_LISTDAILY                   1187
#define IDC_STATIC_NUM                  1191
#define IDC_TIME_PASS                   1192
#define IDC_EXPTOP                      1193
#define IDC_EXPBOT                      1194
#define IDC_BTNSENDLEASE                1195
#define IDC_BTNEBILL                    1196
#define IDC_IE                          1197
#define IDC_BTNTEXT                     1198
#define IDC_IESEND                      1199
#define IDC_BTNTAGCOMP                  1200
#define IDC_BTNMOVE                     1201
#define IDC_BTNIMAGE                    1202
#define IDC_BTNUNLOCK                   1204
#define IDC_BTNCALLRENT                 1205
#define IDC_EDITCODE                    1206
#define IDC_STATICAPT                   1207
#define IDC_EDIT2                       1208
#define IDC_EDITAPTNO                   1208
#define IDC_TEXT_DATE                   1209
#define IDC_TEXT_DATE3                  1211
#define IDC_TEXT_TIME                   1211
#define ID_ADD                          32774
#define ID_DELETE                       32775
#define ID_EDIT                         32779
#define ID_ACCOUNT_ADD                  32784
#define ID_EXIT                         32785
#define ID_ACCOUNT                      32786
#define ID_SETTINGS                     32787
#define ID_WEBSITE                      32788
#define ID_CALL                         32795
#define ID_CHAT                         32796
#define ID_LOG                          32800
#define ID_CLOSEALLTABS_CLOSEALLTABS    32801
#define ID_CLOSEALLTABS                 32802
#define ID__GOTOLASTTAB                 32803
#define ID_GOTOLASTTAB                  32804
#define ID_64347                        32805
#define ID_64348                        32806
#define ID_COPY                         32807
#define ID_SELECT_ALL                   32808
#define ID__COPY                        32809
#define ID__VIDEOCALL                   32810
#define ID_VIDEOCALL                    32811
#define ID_ACCOUNT_CHANGE               32812
#define ID_ACCOUNT_EDIT                 32912
#define ID_ACCOUNT_STUB                 33012
#define ID__CLOSE                       33013
#define ID__UPDATE                      33014
#define ID__HELP                        33015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        294
#define _APS_NEXT_COMMAND_VALUE         33016
#define _APS_NEXT_CONTROL_VALUE         1210
#define _APS_NEXT_SYMED_VALUE           221
#endif
#endif
